# Site settings
# in the templates available like {{ site.myvariable }}.
title: ModellistaIT
email: dm@emanuela.info
brand: Emanuela De Munari
shop: "https://www.etsy.com/shop/ModellistaIT"
headline: ModellistaIT
description: > # this means to ignore newlines until "baseurl:"
  Modellista & sarta
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emanuela.info" # the base hostname & protocol for your site
copyright: 2017 - 2019. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 687665

# Contacts
email: dm@emanuela.info
phone: +393772479874
facebook: @ModellistaIT
etsy: ModellistaIT

# Tracking
googleAnalitycsID: UA-103821879-1
